[package]
name = "luna-jit"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "luna"
path = "src/main.rs"

[lib]
name = "luna"
path = "src/lib.rs"



[target.'cfg(unix)'.dependencies]
libc = "0.2"

[features]
default = ["jit"]
jit = []

[profile.release]
opt-level = 3
lto = true
